# Generated by Django 4.1.7 on 2023-03-03 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SingletonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotUpdateStatus",
            fields=[
                (
                    "singletonmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payment.singletonmodel",
                    ),
                ),
                (
                    "is_update",
                    models.BooleanField(default=True, verbose_name="update status"),
                ),
            ],
            bases=("payment.singletonmodel",),
        ),
        migrations.CreateModel(
            name="PriceSettings",
            fields=[
                (
                    "singletonmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payment.singletonmodel",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Price : Rial")),
                ("usd", models.FloatField(verbose_name="usd : Usd")),
            ],
            bases=("payment.singletonmodel",),
        ),
        migrations.CreateModel(
            name="PerfectMonyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_code",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="voucher_code",
                    ),
                ),
                (
                    "voucher_active",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="voucher_active",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False, verbose_name="Status")),
                ("is_tmp", models.BooleanField(default=True, verbose_name="is_tmp")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_pm_payment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
