# Generated by Django 4.0.1 on 2023-03-08 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_perfectmonypayment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15, verbose_name='Symbol : USDTIRT, TRXIRT, ')),
                ('contract_addres', models.CharField(blank=True, default=None, max_length=90, null=True, verbose_name='contract_addres')),
            ],
        ),
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64, unique=True, verbose_name='Transaction Id')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Status')),
                ('ownerAddress', models.CharField(blank=True, max_length=64, null=True, verbose_name='ownerAddress')),
                ('amount', models.FloatField(blank=True, default=0, verbose_name='amount')),
                ('contract_address', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='contract_address')),
                ('contractRet', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='contractRet')),
                ('srConfirmList', models.IntegerField(blank=True, default=0, verbose_name='srConfirmList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userpayment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Wallat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name : Tron')),
                ('wallat', models.CharField(max_length=90, unique=True, verbose_name='Wallet')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricesettings',
            name='singletonmodel_ptr',
        ),
        migrations.DeleteModel(
            name='PerfectMonyPayment',
        ),
        migrations.DeleteModel(
            name='PriceSettings',
        ),
    ]
