# Generated by Django 3.2.9 on 2023-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230218_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfectmonypayment',
            name='is_tmp',
            field=models.BooleanField(default=True, verbose_name='is_tmp'),
        ),
    ]
