# Generated by Django 4.1.7 on 2023-03-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_contractaddres_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='contractRet',
            new_name='contract_ret',
        ),
        migrations.RenameField(
            model_name='userpayments',
            old_name='ownerAddress',
            new_name='owner_address',
        ),
        migrations.RenameField(
            model_name='userpayments',
            old_name='srConfirmList',
            new_name='sr_confirm_list',
        ),
    ]
