# Generated by Django 3.2.9 on 2023-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_pricesettings_singletonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfectmonypayment',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='voucher_code'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='price',
            field=models.FloatField(verbose_name='Price : Rial'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='usd',
            field=models.IntegerField(verbose_name='usd : Usd'),
        ),
    ]
