# Generated by Django 4.1.7 on 2023-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20230220_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettings',
            name='price',
            field=models.IntegerField(verbose_name='Price : Rial'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='usd',
            field=models.FloatField(verbose_name='usd : Usd'),
        ),
    ]
