# Generated by Django 4.1.7 on 2023-03-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_contractret_userpayments_contract_ret_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallat',
            new_name='Wallet',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='wallat',
            new_name='wallet',
        ),
    ]
