# Generated by Django 4.1.7 on 2023-02-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_pricesettings_price_alter_pricesettings_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUpdate',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.singletonmodel')),
                ('update', models.BooleanField(default=True, verbose_name='update')),
            ],
            bases=('payment.singletonmodel',),
        ),
    ]
