# Generated by Django 3.2.9 on 2023-02-18 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('domain_country', models.CharField(max_length=5, unique=True, verbose_name='Domain Name')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField(unique=True, verbose_name='HashV2ray')),
                ('volume', models.IntegerField(default=150, verbose_name='Volume : MB')),
                ('is_tunel', models.BooleanField(default=False, verbose_name='Is Tunel ?')),
                ('expier_date', models.DateField(verbose_name='Expire Date Time')),
                ('is_use', models.BooleanField(default=False, verbose_name='Is Use This Config?')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_configvpn', to='ray.country', verbose_name='Country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_configvpn', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
