# Generated by Django 4.1.7 on 2023-03-03 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Price : Rial")),
                (
                    "volume",
                    models.IntegerField(default=10240, verbose_name="Volume : MB"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Name")),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="None",
                        max_length=40,
                        null=True,
                        verbose_name="username xui panel",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="None",
                        max_length=40,
                        null=True,
                        verbose_name="password xui panel",
                    ),
                ),
                ("ip", models.CharField(max_length=40, verbose_name="ip Server")),
                (
                    "domain_country",
                    models.CharField(max_length=5, verbose_name="Domain Name"),
                ),
                ("down", models.BooleanField(default=False, verbose_name="Down")),
                (
                    "is_tunnel",
                    models.BooleanField(default=False, verbose_name="Is Tunnel ?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfigVpn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conf", models.TextField(unique=True, verbose_name="HashV2ray")),
                ("uuid", models.TextField(blank=True, null=True, verbose_name="uuid")),
                (
                    "volume",
                    models.IntegerField(default=150, verbose_name="Volume : MB"),
                ),
                (
                    "expire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expire Date Time"
                    ),
                ),
                (
                    "is_use",
                    models.BooleanField(
                        default=False, verbose_name="Is Use This Config?"
                    ),
                ),
                (
                    "last_num_change",
                    models.IntegerField(default=0, verbose_name="Last Change Server"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="server_configvpn",
                        to="ray.server",
                        verbose_name="server",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_configvpn",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
