# Generated by Django 3.2.9 on 2023-02-18 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ray', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=150, verbose_name='Volume : MB')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_order', to='ray.country', verbose_name='Country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
