# Generated by Django 3.2.9 on 2023-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0003_rename_ordere_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceolumeV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=150, verbose_name='Volume : MB')),
                ('price', models.IntegerField(default=300000, verbose_name='Price : Rial')),
            ],
        ),
    ]
