# Generated by Django 4.1.7 on 2023-03-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ray", "0003_proxyconfig_delete_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proxyconfig",
            old_name="conf",
            new_name="proxy_hash",
        ),
    ]
