# Generated by Django 3.2.9 on 2023-02-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0004_priceolumev'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceolumeV',
            new_name='PriceVolume',
        ),
    ]
