# Generated by Django 3.2.9 on 2023-02-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0005_rename_priceolumev_pricevolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvpn',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_configvpn', to='ray.pricevolume', verbose_name='Price'),
        ),
    ]
