# Generated by Django 3.2.9 on 2023-02-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0006_configvpn_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configvpn',
            name='price',
        ),
    ]
