# Generated by Django 3.2.9 on 2023-02-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0007_remove_configvpn_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price : Rial')),
                ('volume', models.IntegerField(default=10240, verbose_name='Volume : MB')),
            ],
        ),
    ]
