# Generated by Django 3.2.9 on 2023-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0008_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
