# Generated by Django 3.2.9 on 2023-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0009_order_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('ip', models.CharField(max_length=40, verbose_name='ip Server')),
                ('domain_country', models.CharField(max_length=5, unique=True, verbose_name='Domain Name')),
            ],
        ),
    ]
