# Generated by Django 3.2.9 on 2023-02-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0010_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='domain_country',
            field=models.CharField(max_length=5, verbose_name='Domain Name'),
        ),
    ]
