# Generated by Django 3.2.9 on 2023-02-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0011_alter_server_domain_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configvpn',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AddField(
            model_name='configvpn',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_configvpn', to='ray.server', verbose_name='server'),
        ),
        migrations.AddField(
            model_name='order',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_order', to='ray.server', verbose_name='server'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
