# Generated by Django 3.2.9 on 2023-02-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0012_auto_20230220_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='down',
            field=models.BooleanField(default=True, verbose_name='Down'),
        ),
    ]
