# Generated by Django 3.2.9 on 2023-02-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0013_server_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(default=None, max_length=40, verbose_name='password xui panel'),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(default=None, max_length=40, verbose_name='username xui panel'),
        ),
    ]
