# Generated by Django 3.2.9 on 2023-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0015_auto_20230220_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, default='None', max_length=40, null=True, verbose_name='password xui panel'),
        ),
        migrations.AlterField(
            model_name='server',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=40, null=True, verbose_name='username xui panel'),
        ),
    ]
