# Generated by Django 3.2.9 on 2023-02-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0016_auto_20230220_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configvpn',
            name='expier_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expire Date Time'),
        ),
    ]
