# Generated by Django 3.2.9 on 2023-02-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0017_alter_configvpn_expier_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_order', to='ray.server', verbose_name='server'),
        ),
    ]
