# Generated by Django 3.2.9 on 2023-02-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0018_alter_order_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceVolume',
        ),
    ]
