# Generated by Django 3.2.9 on 2023-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0019_delete_pricevolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='down',
            field=models.BooleanField(default=False, verbose_name='Down'),
        ),
    ]
