# Generated by Django 3.2.9 on 2023-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0020_alter_server_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configvpn',
            name='expier_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expire Date Time'),
        ),
    ]
