# Generated by Django 3.2.9 on 2023-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0021_alter_configvpn_expier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvpn',
            name='uuid',
            field=models.TextField(blank=True, null=True, verbose_name='uuid'),
        ),
    ]
