# Generated by Django 4.1.7 on 2023-02-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ray", "0022_configvpn_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configvpn",
            old_name="expier_date",
            new_name="expire_date",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
