# Generated by Django 3.2.9 on 2023-02-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanse', models.FloatField(default=0, verbose_name='Balance')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userbalans_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
