# Generated by Django 3.2.9 on 2023-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbalanse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalanse',
            name='balanse',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
