# Generated by Django 4.0.1 on 2023-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_send_ads_user_send_ads_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='wallat',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True, verbose_name='Usser Wallat'),
        ),
    ]
