# Generated by Django 3.2.9 on 2023-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userbalanse_balanse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalanse',
            name='test_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
