# Generated by Django 4.0.1 on 2023-03-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_balance_wallat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='Balance'),
        ),
    ]
