# Generated by Django 4.1.7 on 2023-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_balance_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='wallat',
        ),
        migrations.AddField(
            model_name='balance',
            name='wallet',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True, verbose_name='Usser Wallet'),
        ),
    ]
