# Generated by Django 4.1.7 on 2023-02-24 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_accountbalance_delete_userbalanse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0, verbose_name="Balance")),
                (
                    "test_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_balance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account Balance",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AccountBalance",
        ),
    ]
